server:
  port: 8080
  servlet:
    context-path: /crm
    
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true 
      
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@42.51.78.12:1521:orcl
    url: jdbc:oracle:thin:@192.168.43.75:1521:orcl
    username: CRM01
    password: CRM01
    
mybatis:
  config-location: classpath:conf.xml